### ISSUE TITLE
/usr/bin/ld: xprintidle.o: undefined reference to symbol 'DPMSInfo'

### ISSUE THREAD

**Issue by Ahmed1Elsawy** [g0hl1n/xprintidle#1]
after running `./configure && make`
this command:
`gcc  -g -O2   -o xprintidle xprintidle.o -L -lXext -lXss -lX11`
produces this error message:

> /usr/bin/ld: xprintidle.o: undefined reference to symbol 'DPMSInfo'

I edited the file Makefile.in
changed this
`LDADD = -L@x_libraries@`
into this
`LDADD = @x_libraries@`

and it worked ..
`gcc  -g -O2   -o xprintidle xprintidle.o  -lXext -lXss -lX11`

**Comment by rleitner** [comment]
Thanks for that spot.
That patch is also already in the debian package.
I will push an update shortly.

**Comment by g0hl1n** [comment]
Fixed in [0.2.2](../releases/tag/0.2.2) by 601900e9ec9aa9543e99dbd8102e308b445e423f
