### ISSUE TITLE
Provide an option to follow the idle state of the keyboard alone

### ISSUE THREAD

**Issue by silviubogan** [g0hl1n/xprintidle#10]
`$ xprintidle --keyboard` would show the number of milliseconds since the keyboard was last used.

**Comment by petterreinholdtsen** [comment]
Is there a X protocol call available to get this information?  I am not aware of any such call.  The xprintidle program simply query the X server for the provided information.  It thus depend on support in the X protocol and server implementation to be able to only query for keyboard idleness.

Why would it be useful to only look for when the keyboard was last used?

**Comment by pfrenssen** [comment]
I would like to have this feature to be able to see how long ago the keyboard has been used. For my system `xprintidle` on its own gives bogus results since I have a sensitive mouse which is registering small movements when a door is opened or a truck passes by outside.

**Comment by petterreinholdtsen** [comment]
[Pieter Frenssen]
> I would like to have this feature to be able to see how long ago the
> keyboard has been used. For my system `xprintidle` on its own gives
> bogus results since I have a sensitive mouse which is registering
> small movements when a door is opened or a truck passes by outside.

Then I suggest you contact the developer of the X protocol and X.org, as
well as the developers of Wayland, to get them to provide such
information for xprintidle to use.  This can not be fixed in xprintidle.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by CyberShadow** [comment]
> For my system `xprintidle` on its own gives bogus results since I have a sensitive mouse which is registering small movements when a door is opened or a truck passes by outside.

High tech solution: write a uinput filter which monitors/reports only keyboard activity, or perhaps filters out small mouse movements if it has been otherwise inactive for some time. Low tech solution: put your mouse upside-down before leaving the desk. (I've been using the low-tech solution so far. :))

**Comment by g0hl1n** [comment]
Close as AFAIK this is not possible with the current X.org versions If somebody knows better, please feel free to reopen this issue and provide a PR. Thanks!
