### ISSUE TITLE
Add commandline argument for "human readable" time output

### ISSUE THREAD

**Issue by g0hl1n** [g0hl1n/xprintidle#5]
Add a parameter to specify the time format to output.

**Comment by petterreinholdtsen** [comment]
You mean like 'ls -h' for human readable?

**Comment by g0hl1n** [comment]
Yes, either a simple "human readable" commandline argument or a fully-fleged date string support like 'date -d'. Maybe also both?
What would you prefer?

**Comment by petterreinholdtsen** [comment]
[g0hl1n]
> Yes, either a simple "human readable" commandline argument or a
> fully-fleged date string support like 'date -d'. Maybe also both?
> What would you prefer?

I am perfectly happy with the default number of seconds, and a human
readable "x minutes, y seconds" human readable output.  Doubt the
advantage of coming up with a 'time duration language' ala the 'time
stamp language' of 'date -d' is worth the effort.

Note, I have only used xprintidle programatically, so never needed a
human readable output.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by Schilive** [comment]
I am sorry to bother in an almost 2-year thread. Is this feature still wanted?

**Comment by g0hl1n** [comment]
I guess so. If you step up to implement it, I'll happily merge it :wink:

**Comment by Schilive** [comment]
Thank you for answering. I will give it a try.
